baseURL = 'https://carlosgeodesica.cl/'
languageCode = 'en-us'
title = 'Carlos Morales'
theme = 'beautifulhugo'

[menu]
  [[menu.main]]
    identifier = "astrophotography"
    name = "Astrophotography"
    url = "/astrophotography/"
    weight = 1

  [[menu.main]]
    identifier = "research"
    name = "Research"
    url = "/research/"
    weight = 2